### ISSUE TITLE
Add note that window.orientation should only be exposed for non-Desktop UAs

### ISSUE THREAD

**Issue by miketaylr** [whatwg/compat#10]
It doesn't make much sense to expose it on Desktop and currently neither Chrome nor Safari do.

**Comment by dmethvin** [comment]
I don't know how those [pivoting monitors](http://www.pcworld.com/article/2042888/review-three-widescreen-hd-monitors-that-pivot-from-portrait-to-landscape.html) interact with the OS. I'm assuming if the browser window size changed on pivoting the monitor they'd get a resize event (if the window size did change), but not necessarily handle orientation.

**Comment by miketaylr** [comment]
Yeah, who knows. I should probably buy one of each to test.
