### ISSUE TITLE
add -webkit-box-orient

### ISSUE THREAD

**Issue by heycam** [whatwg/compat#113]
The -webkit-line-clamp definition in https://drafts.csswg.org/css-overflow-3/#webkit-line-clamp needs to refer to the -webkit-box-orient property, since the legacy line clamping behavior only occurs when that property is "vertical".  Given #87 I think we just want to add it to the "Property mappings" and say it's a mapping for flex-direction (even though all of these -webkit-box-* properties are not really mappings/aliases), and not bother mentioning anything about the specific keyword mappings.

cc @dholbert

**Comment by heycam** [comment]
cc @fantasai @frivoal

**Comment by frivoal** [comment]
+1

The behavior of webkit-box and flexbox are sufficiently different that in the long run, we're going to need a full spec for it (probably as an appendix to the flexbox spec) but until then, we should at least spec the syntax, and the compat spec seems like a good place for that.

**Comment by gsnedders** [comment]
fixed by #114

**Comment by miketaylr** [comment]
Indeed it was, thanks!
