### ISSUE TITLE
Chrome is more lax than Firefox with XSL errors.

### ISSUE THREAD

**Issue by wisniewskit** [whatwg/compat#120]
Firefox is more strict than Chrome about XSL errors, and it's unclear to me if that is something we wish to act  upon.

For instance, Firefox throws an error when `<xsl:stylesheet>` is missing a `version` attribute, or when an `xsl:output method` is not `"text"`, `"html"`, or `"xml"`. Chrome seems to ignore the missing `version` and go ahead with `1.0`, and also ignore the `output` method entirely in favor of just transforming as `html` no matter what value is actually given.

I'm personally unaware of any actual webcompat fallout from this, but I wouldn't be surprised if it is a pain point for developers, as I recently spoke with a dev on Reddit about Firefox throwing unclear errors (in their case they happened to specify "xhtml" as an output method, which Chrome happily accepted, but Firefox reported an error).

So if XSL is not removed from the web platform anytime soon, it might be worth checking if and how implementations should align on these kinds of cases.

**Comment by cvrebert** [comment]
Possibly overlaps with https://github.com/whatwg/dom/issues/181 more generally.

**Comment by miketaylr** [comment]
Yeah, it looks like parts of this are starting to get defined in DOM. So let's close here - thanks for the research @wisniewskit.
