### ISSUE TITLE
Spec -webkit-mask-*

### ISSUE THREAD

**Issue by karlcow** [whatwg/compat#14]
Again just here for getting a better understanding of how widespread is it. 

Currently the tier1 version of google search is using [`-webkit-mask-image`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-mask-image) and `-webkit-mask-size`. See https://bugzilla.mozilla.org/show_bug.cgi?id=921532 To note that Google is serving an inferior version to Firefox and IE where they get links at the bottom instead of infinite loading and CSS sprites instead of the mask.

About CSS Masks usage http://caniuse.com/#feat=css-masks
The support is not overlapping. aka Webkit/Blink family supports only -webkit-mask-image, etc.
And Gecko supports only SVG masks.
And Trident/Edge doesn't support anything.

We have a case of non overlapping feature.

@foolip I wonder if there are data on how widespread the usage is on the Web for Chrome?

**Comment by foolip** [comment]
You can find this data at https://www.chromestatus.com/metrics/css/popularity

However, if these are being used by Google search, then that'll dominate the usage so we'll have no idea how risky it would be to remove until Google search stops using it.

Not sure who the best contact for this in Blink would be. I guess it's style+paint? @dirkschulze @rbyers, do you know?

**Comment by karlcow** [comment]
Thanks @foolip 
ah. indeed. I wish there was a popularity by unique domains (aka this property is used on *n* domains).

**Comment by karlcow** [comment]
As of today 

* ~ 7.5% `webkit-mask-image`: https://www.chromestatus.com/metrics/css/timeline/popularity/289
* ~ 4.9% `webkit-mask-size`: https://www.chromestatus.com/metrics/css/timeline/popularity/297
* ~0.15% `mask`: https://www.chromestatus.com/metrics/css/timeline/popularity/357

**Comment by karlcow** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=686281

**Comment by miketaylr** [comment]
We aliased a handful (all?) of the CSS mask props to -webkit-mask props here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1242617

See http://hg.mozilla.org/mozilla-central/rev/f6eba571ce59 for actual mappings.

TODO:

- [ ] Make sure this actually works the way we think it should
- [ ] Spec it

@karlcow do you know offhand of any sites that use these props we can test against? (I can probably find some easily if you don't)

**Comment by miketaylr** [comment]
Gonna pile some demos from quick googling here. To investigate failures.

- https://jedidiah.eu/code/css/masks/, the second animated demo works as expected. The first heart mask doesn't -- but it doesn't in Chrome or Safari either.

- https://css-tricks.com/examples/ImageWipes/ doesn't work in Fx Nightly.

- http://tympanus.net/codrops/css_reference/mask-image/ half works in Fx Nightly (possibly we don't support gradient masks yet?)

- http://vanseodesign.com/css/clipping-and-masking-examples/ lots of examples and links to look at here.

https://github.com/WebKit/webkit/tree/master/LayoutTests/fast/masking

**Comment by miketaylr** [comment]
Going to update the title, because this is something we feel important enough to support in Gecko.

**Comment by miketaylr** [comment]
Here's a naive guess at how mapping should happen (I think a few things were left out of the commit at http://hg.mozilla.org/mozilla-central/rev/f6eba571ce59):

| Chrome usage stats |WebKit Mask Property | Standard Equivalent (if any) |
| ------------- | ------------- | ------------|
| [1.3352%](https://www.chromestatus.com/metrics/css/popularity#webkit-mask)| -webkit-mask | mask |
| [0.5929%](https://www.chromestatus.com/metrics/css/popularity#webkit-mask-box-image)| -webkit-mask-box-image | mask-border :question:  |
| *none* | *none* :question:  | mask-border-mode |
| [0.0094%](https://www.chromestatus.com/metrics/css/popularity#webkit-mask-box-image-outset)| -webkit-mask-box-image-outset | mask-border-outset (?) |
| [0.0097%](https://www.chromestatus.com/metrics/css/popularity#webkit-mask-box-image-repeat)| -webkit-mask-box-image-repeat | mask-border-repeat (?) |
| [0.0097%](https://www.chromestatus.com/metrics/css/popularity#webkit-mask-box-image-slice)| -webkit-mask-box-image-slice | mask-border-slice (?) |
| [0.0098%](https://www.chromestatus.com/metrics/css/popularity#webkit-mask-box-image-source)| -webkit-mask-box-image-source | mask-border-source (?) |
| [0.0093%](https://www.chromestatus.com/metrics/css/popularity#webkit-mask-box-image-width)| -webkit-mask-box-image-width | mask-border-width (?) |
| [0.0161%](https://www.chromestatus.com/metrics/css/popularity#webkit-mask-clip)| -webkit-mask-clip | mask-clip |
| [0.0142%](https://www.chromestatus.com/metrics/css/popularity#webkit-mask-composite)| -webkit-mask-composite | mask-composite |
| [4.9836%](https://www.chromestatus.com/metrics/css/popularity#webkit-mask-image)| -webkit-mask-image | mask-image |
| *none* | *none* :question:  | mask-mode |
| [0.0093%](https://www.chromestatus.com/metrics/css/popularity#webkit-mask-origin)| -webkit-mask-origin | mask-origin |
| [1.6921%](https://www.chromestatus.com/metrics/css/popularity#webkit-mask-position)| -webkit-mask-position | mask-position |
| [0.0058%](https://www.chromestatus.com/metrics/css/popularity#webkit-mask-position-x)| -webkit-mask-position-x | *none* :question:  |
| [0.0034%](https://www.chromestatus.com/metrics/css/popularity#webkit-mask-position-y)| -webkit-mask-position-y | *none* :question:  |
| [2.0105%](https://www.chromestatus.com/metrics/css/popularity#webkit-mask-repeat)| -webkit-mask-repeat | mask-repeat |
| [<=0.0001%](https://www.chromestatus.com/metrics/css/popularity#webkit-mask-repeat-x)| -webkit-mask-repeat-x | *none* :question:  |
| [<=0.0001%](https://www.chromestatus.com/metrics/css/popularity#webkit-mask-repeat-y)| -webkit-mask-repeat-y | *none* :question: |
| [2.6887%](https://www.chromestatus.com/metrics/css/popularity#webkit-mask-size)| -webkit-mask-size | mask-size |
| none | -webkit-mask-source-type | mask-type :question:  |

Stuff with :question:  is just a guess, based on naming similarities and descriptions. Need to look more closely.

TODO: Look at props that take keywords and see if values between the two are the same.

**Comment by karlcow** [comment]
@miketaylr Well I was about to suggest images.google.com as the biggest offender… but testing it this morning I was… in shock!

They fixed it: https://bugzilla.mozilla.org/show_bug.cgi?id=921532#c17 for Chrome and use SVG.
From a quick test it seems, we could ask them to send us this version. I need to further test it.

**Comment by miketaylr** [comment]
> @miketaylr Well I was about to suggest images.google.com as the biggest offender… but testing it this morning I was… in shock!

Cool! OK, I'll keep testing demos then and find other sites in my bugmail.

**Comment by miketaylr** [comment]
A few notes from research.

Safari originally shipped a `-webkit-mask-attachment` (it's listed in the original blog post), but that was removed. See http://mac-os-forge.2317878.n4.nabble.com/CSS-Masking-in-WebKit-td191605.html and  https://bugs.webkit.org/show_bug.cgi?id=67137. Apparently it was never actually implemented for content so there shouldn't be any compat concerns here.

`-webkit-mask-repeat-x` and `-webkit-mask-repeat-y` are a 0 usage, according to Chrome usage.

Will have to keep an eye on `-webkit-mask-position-x` and `-webkit-mask-position-y` -- it looks like a recent-ish uptick in usage (possibly some popular lib or framework started using them?).

**Comment by miketaylr** [comment]
I'll double check the `-box-image-` -> `-border-` aliases before adding those to the spec.

**Comment by miketaylr** [comment]
I should probably remove `-webkit-mask-source-type` -- Chrome doesn't support this (WebKit added support shortly after the Blink split). And hopefully when Chrome does add support, they'll just add support for `mask-type` without a prefix.

(Let's keep an eye out for web content that depends on this, but I suspect it would be very, very low).

**Comment by karlcow** [comment]
158 code results.
I github standards almost none 
https://github.com/search?langOverride=&q=-webkit-mask-source-type&repo=&start_value=1&type=Code

**Comment by miketaylr** [comment]
Yep, most of those just forks of WebKit tests.

**Comment by miketaylr** [comment]
Based on https://developer.apple.com/library/safari/documentation/InternetWeb/Conceptual/SafariVisualEffectsProgGuide/Masks/Masks.html, https://github.com/WebKit/webkit/blob/master/Source/WebCore/css/CSSPropertyNames.in#L548, and stuff like http://www.html5rocks.com/en/tutorials/masking/adobe/#toc-the-mask-border-property I'm fairly confident the main difference between `-webkit-mask-box-image` and `mask-border` properties is just the name.

Compating between https://www.w3.org/TR/2013/WD-css-masking-20130620/#box-image-masks and
https://drafts.fxtf.org/css-masking-1/#mask-borders, the only difference I see is the equivalent of a `mask-border-mode` from `-webkit-mask-box-image`, but it should just be set to its initial value (`alpha`).

**Comment by karlcow** [comment]
6 years later no browsers are implementing `mask-border` and variants. We should probably remove `-webkit-mask-box` from the legacy alias name, and move them to a section where we say that they need to be supported on their own.
