### ISSUE TITLE
[uastring] Create a document in this repo collecting information about UA string reduction/freezing

### ISSUE THREAD

**Issue by karlcow** [whatwg/compat#146]
We already have https://github.com/whatwg/compat/blob/main/compatibility.bs

We could have a second one called `uastring.bs`

**Comment by miketaylr** [comment]
Awesome, thanks Karl. Seems fine to me to start something here, and if it should graduate to some other spec, even better.

**Comment by gsnedders** [comment]
What's the goal of the document? To document best practice for defining a UA string, or to explain trade-offs between privacy and other goals?

**Comment by karlcow** [comment]
@gsnedders there is a "regular" meeting to discuss things. Do you want me to add you?

We want to document 

1. What is being done
2. What can be frozen without creating too many compat issues.

And we probably want to assume that the 2. is not tied to UA client hints. Aka what can we freeze even if UA client hints do not exist.

**Comment by gsnedders** [comment]
> @gsnedders there is a "regular" meeting to discuss things. Do you want me to add you?

Probably not worthwhile?

**Comment by miketaylr** [comment]
I think I'll start a PR in the main compat standard as a new section, then we can consider moving it to its own thing if it makes sense (less activation energy).
