### ISSUE TITLE
Spec -webkit-min-device-pixel-ratio

### ISSUE THREAD

**Issue by miketaylr** [whatwg/compat#15]
We've seen a number of busted sites in Firefox mobile browsers due to media queries using this (and only this).

@dholbert is implementing in Gecko in https://bugzilla.mozilla.org/show_bug.cgi?id=1176968

**Comment by dholbert** [comment]
Some documentation (in blog post form) from Hyatt on this feature:
 https://www.webkit.org/blog/55/high-dpi-web-sites/

Pseudo-documentation from W3C (about how it relates to the standardized "resolution" media query):
 http://www.w3.org/blog/CSS/2012/06/14/unprefix-webkit-device-pixel-ratio/

**Comment by foolip** [comment]
This isn't too surprising, this is one of four media features where the usage was too high to remove:
https://www.chromestatus.com/metrics/feature/timeline/popularity/233
https://www.chromestatus.com/metrics/feature/timeline/popularity/234
https://www.chromestatus.com/metrics/feature/timeline/popularity/235
https://www.chromestatus.com/metrics/feature/timeline/popularity/237

A few others were successfully removed:
https://groups.google.com/a/chromium.org/d/msg/blink-dev/RO9K26CeuhI/ZWIx0Tb1LHgJ
https://groups.google.com/a/chromium.org/d/msg/blink-dev/lYZC-Xqf_Gw/D6Or7mZHwr4J

**Comment by miketaylr** [comment]
Gecko doesn't implement this in terms of `dppx`, but that seems like the easiest way to describe it. (Probably at some point I'll change the MUST to a MAY, with some language around implementation details).

**Comment by miketaylr** [comment]
For fun, I did a GitHub search for `-webkit-max-device-pixel-ratio` and got exactly 1 hit. Non-scientific, but kinda funny.

https://github.com/search?q=webkit-max-device-pixel-ratio&ref=searchresults&type=Code&utf8=%E2%9C%93

**Comment by dholbert** [comment]
Your search is missing the initial "-". If you include that, you get 9500 results:
https://github.com/search?utf8=%E2%9C%93&q=-webkit-max-device-pixel-ratio&type=Code&ref=searchresults

**Comment by miketaylr** [comment]
Ah, so the funny result is just my awesome search skills. Still low enough on GitHub for me to feel good about ignoring it.

Thx @dholbert .

**Comment by dholbert** [comment]
I missed that we were ignoring it. If we're speccing webkit-device-pixel-ratio and webkit-min-device-pixel-ratio, I'd expect we should spec "max" as well for completeness...

(Really, these are all flavors of the webkit-prefixed "device-pixel-ratio" proposal, and it feels odd to mention two without mentioning the third.  And as long as someone's implementing the spec for two of these, it doesn't really add any extra complexity for them to also implement the third.)

**Comment by miketaylr** [comment]
Sure, that's fair. I guess it is kind of weird to spec only one end of a range feature type. Lemme add those.

**Comment by zcorpan** [comment]
Um, you shouldn't use "may" because it can be implemented in other ways that give the same end result. Anything that gives the same end result perfectly satisfies a "must" requirement.

Also, the way media features are defined, I think you need to special-case -webkit-min-* and -webkit-max-*. The spec allows min- and max- prefixes for range media features, it doesn't define e.g. min-resolution as a separate media feature. So if you define -webkit-min-device-pixel-ratio as a range media feature, that technically means you also define min-webkit-min-device-pixel-ratio and max-webkit-min-device-pixel-ratio.

cc @tabatkins for how to spec this properly. Maybe the MQ spec should deal with this directly?

**Comment by miketaylr** [comment]
> Anything that gives the same end result perfectly satisfies a "must" requirement.

OK, thanks.

> So if you define -webkit-min-device-pixel-ratio as a range media feature, that technically means you also define min-webkit-min-device-pixel-ratio and max-webkit-min-device-pixel-ratio.

Hmm. Yeah, that's not what we want.

**Comment by dholbert** [comment]
Yeah -- in Gecko, with `-moz` prefixed media queries, we expect "min-" and "max-" to be *before* the vendor-prefix, so we accept e.g. `min--moz-device-pixel-ratio`, *not* `-moz-min-device-pixel-ratio`.  This is correct, I think, as @zcorpan describes here.

WebKit's decision to put the vendor prefix always first (even before `min-`/`max-` modifiers) is indeed quirky (though arguably a little easier on the eyes).

I'm not a spec editor, but IMO it should be OK to just call this out as a hand-wavy exception to how `min-` & `max-` work with media queries.

**Comment by zcorpan** [comment]
Yeah, I think define -webkit-device-pixel-ratio as a range media feature; say that min- and max- prefixes must not apply to it, instead -webkit-min-device-pixel-ratio must act as an alias of what would-be min--webkit-device-pixel-ratio (and similarly for max).

**Comment by miketaylr** [comment]
@zcorpan does https://compat.spec.whatwg.org/#css-media-queries-webkit-device-pixel-ratio look better?

**Comment by zcorpan** [comment]
Yes. Lgtm

-- 
Simon Pieters

**Comment by zcorpan** [comment]
Just one more thing... (sorry)

You also need to say that the Value is a &lt;number> rather than a &lt;resolution>. Right now `-webkit-device-pixel-ratio: 2.0` would fail to parse but `-webkit-device-pixel-ratio: 192dpi` would parse as `resolution: 192dppx`.

**Comment by miketaylr** [comment]
:+1:
