### ISSUE TITLE
Add a dfn for simple alias

### ISSUE THREAD

**Issue by miketaylr** [whatwg/compat#154]
As noted in https://github.com/whatwg/compat/issues/153#issuecomment-891219329, this isn't actually defined or linkable.

**Comment by gsnedders** [comment]
we want to use the terms defined in https://drafts.csswg.org/css-cascade-5/#aliasing

**Comment by gsnedders** [comment]
ah, I thought this had already been reported, and it had: #121

**Comment by miketaylr** [comment]
Thanks @gsnedders - this also felt familiar. Let's close here in favor of #121.
