### ISSUE TITLE
Are these features really "non-standard"?

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/compat#165]
https://compat.spec.whatwg.org/

> This standard describes a collection of non-standard (and often vendor-prefixed) CSS properties and DOM APIs that web browsers need to support for compatibility with the de facto web.

Are these features really "non-standard" given that they're now specified in the Compatibility Living Standard?

For example, from https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-webkit-device-pixel-ratio

> **Non-standard:** This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

I think this warning on MDN is incorrect. `-webkit-min-device-pixel-ratio` is more reliable than `min-resolution`, since the latter is not supported in Safari, whereas the former has excellent browser support.

Should features specified in the Compatibility Living Standard be considered deprecated?

**Comment by miketaylr** [comment]
> Are these features really "non-standard" given that they're now specified in the Compatibility Living Standard?

I suppose they were non-standard until we specified them (not making claims I did a great job for most of them!), and now they've grown into beautiful swans. 🦢 

Do you have any recommendation of how to improve? Maybe just remove non-standard?

> Should features specified in the Compatibility Living Standard be considered deprecated?

Some perhaps, where better alternatives exist. Perhaps I will find the time to start addressing https://github.com/whatwg/compat/issues/156, which is one way to identify what should be considered deprecated vs "specced in this doc".

**Comment by jakearchibald** [comment]
I think removing "non-standard" is good, and mark particular features as deprecated if there's a reasonable path to remove it. In the case of `-webkit-device-pixel-ratio` I don't think it can be deprecated yet due to lack of Safari support for `resolution`.

**Comment by jakearchibald** [comment]
Cheers fella!
