### ISSUE TITLE
Spec -webkit-border-image

### ISSUE THREAD

**Issue by miketaylr** [whatwg/compat#17]
It's one of the -webkit- prefixes supported by Edge, and a number of high priority mobile sites depend on it ([goog calendar](https://bugzilla.mozilla.org/show_bug.cgi?id=995140) and gmail being two).

According to Chrome platform status, usage currently hovers right around 1% of page loads:
https://www.chromestatus.com/metrics/css/timeline/popularity/196

http://dbaron.org/log/20120612-border-image is a good resource for why this *can't* be a simple alias to unprefixed border-image.

Here's a simple test page with some code from google calendar: http://jsbin.com/gafinudopa/4/edit?html,css,output.

Both Chrome and Edge have the same output.

@jacobrossi - is there someone who worked on `-webkit-border-image` who would be willing to share notes on how y'all implemented it?

**Comment by miketaylr** [comment]
(They could email  me at miket@mozilla.com if they're more comfortable with less public feedback. :see_no_evil: :heart:)

**Comment by miketaylr** [comment]
A Blink UseCounter just landed today to track "border-image overriding border-widths" (see https://code.google.com/p/chromium/issues/detail?id=356802): https://chromium.googlesource.com/chromium/src.git/+/235538d4c5836ab7651ae54ce04360eca362089d

**Comment by miketaylr** [comment]
https://code.google.com/p/chromium/issues/detail?id=559258#c14 suggests that Edge has added bug compatibility with Blink/WebKit's current "(unprefixed) `border-image` overrides `border-style`" bug... but it sounds like they are willing to revert if some Google properties are fixed?

In order for `-webkit-border-image` to work as an alias to unprefixed `border-image` these quirks would have to be added, which seems not good.

**Comment by foolip** [comment]
CC @doomdavve

**Comment by miketaylr** [comment]
It looks like WebKit just fixed their "border-image doesn't honor border-style" bug today: https://bugs.webkit.org/show_bug.cgi?id=99922

**Comment by karlcow** [comment]
They still have a couple of issues with tests on windows. 
I also wonder if the fix breaks some sites.

**Comment by miketaylr** [comment]
> I also wonder if the fix breaks some sites.

It's possible. (cc @Adenilson who wrote the WebKit + Blink patches).

**Comment by Adenilson** [comment]
@karlcow The windows bot failure is not an issue anymore.

That been said, I just tested mobile gcalendar and it will fail (i.e. not render rounded buttons) in both Blink and WebKit patched.

I think the solution here is to push google to fix their code (i.e. gcalendar/gmail) otherwise all web engines (Edge, FF, WebKit, Blink) will be stuck having to support the quirk.

Please see attached screeenshots.

<img width="982" alt="screen shot 2015-12-02 at 9 32 47 pm" src="https://cloud.githubusercontent.com/assets/959744/11552929/e730f754-993e-11e5-93de-bd887e77e5df.png">
<img width="1077" alt="screen shot 2015-12-02 at 9 40 15 pm" src="https://cloud.githubusercontent.com/assets/959744/11552928/e72eb142-993e-11e5-90da-147186cf3a44.png">

**Comment by karlcow** [comment]
+1 to push Google. It's one of the issue identified in 
https://bugzilla.mozilla.org/show_bug.cgi?id=914252#c17
https://bug914252.bmoattachments.org/attachment.cgi?id=8689920

**Comment by Adenilson** [comment]
Just confirmed that MS Edge had to implement the quirk, please see attached screenshots.
<img width="806" alt="screen shot 2015-12-03 at 2 12 43 pm" src="https://cloud.githubusercontent.com/assets/959744/11575985/c3e2110e-99c8-11e5-9181-7c71d74bd123.png">
<img width="810" alt="screen shot 2015-12-03 at 2 13 27 pm" src="https://cloud.githubusercontent.com/assets/959744/11575986/c3e6d50e-99c8-11e5-9b5a-24c1e01c707d.png">

**Comment by miketaylr** [comment]
(Note here for future self, which is probably obvious to everyone except me: Blink/WebKit browsers never shipped longhand `-webkit-` prefixed border-image properties. Just the shorthand).

**Comment by Adenilson** [comment]
Just posted this in www-style:
https://lists.w3.org/Archives/Public/www-style/2015Dec/0080.html

**Comment by Adenilson** [comment]
For reference, the intent to implement in Blink:
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/J7rvFkcn8TU

**Comment by Adenilson** [comment]
An update: it seems that google calendar mobile was fixed:
https://code.google.com/p/chromium/issues/detail?id=559258#c37

**Comment by Adenilson** [comment]
How gcalendar looks in FF.
<img width="469" alt="screen shot 2016-02-01 at 4 03 32 pm" src="https://cloud.githubusercontent.com/assets/959744/12735527/7a965618-c8fd-11e5-9630-9ce392c66202.png">

**Comment by karlcow** [comment]
Thanks @Adenilson I also added
https://bugzilla.mozilla.org/show_bug.cgi?id=914252#c21

**Comment by Adenilson** [comment]
There is new activity on the intent to implement and ship the change in Chromium:
https://groups.google.com/a/chromium.org/forum/#!searchin/blink-dev/border-image/blink-dev/J7rvFkcn8TU/OtIcXTDDAQAJ

Basically, if anyone of you guys have data about the use of border-image *with* no border defined, it would be the perfect moment to share this information.

Otherwise we ran the risk of having the quirk spec'ed as part of the -webkit-border-image (which would force FF to implement the behavior).

**Comment by Adenilson** [comment]
An update: the change has received 3 LGTM and should land on chrome M51.

**Comment by miketaylr** [comment]
Great news, thanks for the update @Adenilson!

**Comment by karlcow** [comment]
Some more recent text for Google Mail on Firefox Android which is almost there, just missing a keyword on border-image. 
(to note we still have a difference of rendering in between Blink and Firefox, but I would call that a separate issue.)

See https://github.com/webcompat/web-bugs/issues/1333#issuecomment-184456835

**Comment by Adenilson** [comment]
For chrome M50, we will land a patch deprecating the old quirky behavior for the property.

**Comment by karlcow** [comment]
There is a difference of behavior currently for gmail. 
I'm not sure I have found yet all details. But it would be interesting to test in Chrome M51
http://www.otsukare.info/2016/02/25/border-image-css

**Comment by Adenilson** [comment]
Update: I landed the deprecation warning for the quirky behavior 3 days ago: https://codereview.chromium.org/1702503002

**Comment by Adenilson** [comment]
Update: I submitted a patch fixing the behavior (as soon it lands, I will report back).

**Comment by Adenilson** [comment]
Another update: it seems that mobile gmail was fixed (but should take a few weeks to hit production)
https://bugs.chromium.org/p/chromium/issues/detail?id=559258#c56

**Comment by Adenilson** [comment]
The patch has landed and I marked the bug as fixed:
https://bugs.chromium.org/p/chromium/issues/detail?id=559258#c59

**Comment by Adenilson** [comment]
Should we close this issue?

**Comment by karlcow** [comment]
@Adenilson About

> The patch has landed and I marked the bug as fixed:

That's great news. 

Does that mean the site using `-webkit-border-image` will break, or did Google just fixed `border-image` (which is cool in itself). I'm asking because if `-webkit-border-image` is not dropped, it probably means that the webcompat issue will continue to exist.

**Comment by Adenilson** [comment]
Karl

Starting with M51, any website using either border-image and the prefix (e.g. -webkit-border-image) must have the border-style defined for the elements using a border image.

If it is not defined, the border is not rendered as that is normative on the spec (i.e. border-style None must not render a border).

That is how things are on the browser side of the equation.

Adenilson

**Comment by miketaylr** [comment]
So the relationship will be like that of `border-image` and `-moz-border-image`: no `border-style` quirks in the prefixed or unprefixed form.

**Comment by Adenilson** [comment]
That being said, I still have to push the fix in WebKit (and only apple knows when that should hit the hands of the users as Safari and iOS has its own release cycle).

**Comment by miketaylr** [comment]
> Just learned that MS has fixed Edge, it will be made available in the next Windows Insider build.

Just to clarify @Adenilson, they fixed Edge to remove the quirky behavior?

**Comment by miketaylr** [comment]
> Should we close this issue?

Yeah, let's do it. Thanks for your help landing the patches in Blink (and soon WebKit) @Adenilson! ❤️ 

I just closed the Gecko bug to implement the quirk as WONTFIX.

**Comment by Adenilson** [comment]
@miketaylr yep, MS has fixed the quirky behavior on MS Edge (being available in the next Windows Insider build).
