### ISSUE TITLE
Highlight changeable parts of the UA string in the examples

### ISSUE THREAD

**Issue by domenic** [whatwg/compat#170]
One of the most interesting things about UA strings is how they differ, both between platforms of the same browser and between versions of the same browser within a platform.

Although you can kind of figure this out from the prose, e.g. it says that on desktop `<geckoVersion>` is frozen as `"20100101"`, I think the examples could make this clear at a glance with some extra markup.

Here is a quick mockup of what this would look like using `<mark>`. It only marks up differences within the same platform; maybe a different-color `<mark>` could be used for highlight the mobile-vs.-desktop differences, or maybe that's not necessary since they're already side-by-side:

![image](https://user-images.githubusercontent.com/617481/152025343-bdf86b93-9252-4043-a69a-c5c28f03b7da.png)

**Comment by miketaylr** [comment]
That's a cool suggestion, I like it.
