### ISSUE TITLE
Tokens are sometimes constants, sometimes partially-constant, sometimes variable

### ISSUE THREAD

**Issue by domenic** [whatwg/compat#172]
I'm unclear on the logic on why sometimes constant values are counted as tokens, versus just put directly into the user agent string.

For example, `<legacyMozillaVersion>` is always the same value. Is it helpful to abstract it away? Why not just inline it wherever it appears?

Similarly, the constants at the beginning and end of `<frozenWebKitVersion>` and `<frozenSafariVersion>` are always constant. Why mix together constant pieces, and actually-varying pieces, in those definitions?

IMO it would be easier to understand if the tokens were only for things that varied. So then the formats would be something like

```
Mozilla/5.0 (<platform>; <oscpu>) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/<chromeVersion> <deviceCompat>Safari/537.36

Mozilla/5.0 (<platform>; <oscpu> rv:< firefoxVersion>) Gecko/<geckoVersion> Firefox/<firefoxVersion>
```

My guess is that the current version's use of tokens is attempting to highlight commonalities, even if those commonalities are a mix of: constants, partially-constants, and totally-variable values. So, please feel free to ignore and close this feedback if you think highlighting commonalities this way is the best path. But IMHO the way in which it's not clear which kind of thing tokens really represent makes them a bit hard to understand.

**Comment by miketaylr** [comment]
> My guess is that the current version's use of tokens is attempting to highlight commonalities, even if those commonalities are a mix of: constants, partially-constants, and totally-variable values. 

Yeah, this is initially what I was going for. But I don't feel super strongly about it - treating tokens as variables is probably a less confusing approach. Thanks for the feedback.
