### ISSUE TITLE
Safari UA string example seems wrong

### ISSUE THREAD

**Issue by domenic** [whatwg/compat#173]
https://compat.spec.whatwg.org/commit-snapshots/3ca5920dc59b351756399bab9ded097d963a799f/#safari-ua-examples

It contains `Chrome/96.0.4664.93 Safari/537.36` but I think it should be `Version/15.2 Safari/605.1.15`

**Comment by miketaylr** [comment]
Hmm, this is probably an accidental copypasta error. Thanks for flagging.
