### ISSUE TITLE
Safari probably needs some kind of <platform-ish> token

### ISSUE THREAD

**Issue by miketaylr** [whatwg/compat#180]
On desktop it's all frozen, but it does change if you're on an iPad vs iPhone, etc. I'm not sure if the mobile parts are frozen, or if they reveal the current iPhone OS (or iPad OS?).

**Comment by gsnedders** [comment]
For mobile mode (i.e., not when you choose to load desktop sites, which is the default on iPadOS):

Mozilla/5.0 (**iPhone**; CPU iPhone OS **15_1** like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/**15.1** Mobile/15E148 Safari/604.1

…where the bold bits change.

**Comment by miketaylr** [comment]
Thanks @gsnedders!

**Comment by miketaylr** [comment]
ok, 

* `Mozilla/5.0 (iPhone; CPU iPhone OS 15_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Mobile/15E148 Safari/604.1`
* `Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1`
* `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15`
* `Mozilla/5.0 (iPod touch; CPU iPhone OS 15_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Mobile/15E148 Safari/604.1`
* `Mozilla/5.0 (iPad; CPU OS 15_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Mobile/15E148 Safari/604.1`

There's like ~2 things going on. 
`<mobileProduct>; CPU iPhone OS 15_1 like Mac OS X` or `Macintosh; Intel Mac OS X 10_15_7`

**Comment by karlcow** [comment]
@gsnedders might confirm  but I think there is a difference in iPad in between ipad mini (gets mobile UA) and ipad (gets desktop UA), because on Firefox on iPad, there are time to time webcompat issues as Mozilla Firefox on iOS sends desktop for both ipad and ipad mini.

**Comment by miketaylr** [comment]
Ah, good call. Maybe when I'm at the mall next I can test an iPad mini. :)
