### ISSUE TITLE
Safari section probably needs further work

### ISSUE THREAD

**Issue by myakura** [whatwg/compat#188]
I saw https://github.com/whatwg/compat/pull/187 right after I checked Safari UAs in a retail store. What a coincidence.

Here are the devices and their UA strings I checked:

iPhone SE (3rd gen, 2022):

```
Mozilla/5.0 (iPhone; CPU iPhone OS 15_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1
```

iPad mini (6th gen, 2021):

```
Mozilla/5.0 (iPad; CPU OS 15_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1
```

iPad Air (5th gen, 2022):

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
```

iPad Pro 11" (3rd gen, 2021):

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
```

So, like @karlcow said in https://github.com/whatwg/compat/issues/180#issuecomment-1079571138 , Safari on iPad has different configurations depending on their form factors; smaller devices report Mobile-ish strings, larger devices report as if they were Mac.

If I recall correctly, iPad changed to report desktop UAs with the introduction of iPadOS. I haven't checked with 12.9" Pro and 10.2". But I guess non-mini iPads report desktop-ish strings by default...?

There are other things to note:

* the OS version after `Mac OS X` on larger iPads is `10_15_6`, not `10_15_7` that is what Safari on macOS reports
* the last version token (`Safari/**`) on smaller devices is `Safari/604.1` and is not the same as `<safariVersion>`

**Comment by miketaylr** [comment]
I wonder if the 604.1 is a constant, or just updated at a different pace than other UAs?

I would be curious to know what the `applicationName` value passed to https://github.com/WebKit/WebKit/blob/daf65f7252fae53104aac1e530d887888daa2d34/Source/WebCore/platform/ios/UserAgentIOS.mm#L84 is - but it seems like that part isn't open source.

**Comment by karlcow** [comment]
604.1 is a constant.

**Comment by gsnedders** [comment]
> If I recall correctly, iPad changed to report desktop UAs with the introduction of iPadOS. I haven't checked with 12.9" Pro and 10.2". But I guess non-mini iPads report desktop-ish strings by default...?

IIRC, there's no difference between explicitly requesting a desktop site on iOS and the desktop default on larger iPadOS devices.

> the OS version after Mac OS X on larger iPads is 10_15_6, not 10_15_7 that is what Safari on macOS reports

Yeah, Safari on macOS originally had it capped to 10_15_6 on macOS 11+, but then this was changed to 10_15_7 when macOS 10.15.7 shipped; apparently desktop-mode iOS/iPadOS never changed, which I've occasionally thought I ought to fix, but haven't.

> Mostly curious about the "Mobile/15E148 Safari/604.1" bit at the end.

15E148 is also a constant (which seems to be a build number [slightly before iOS 11.3](https://en.wikipedia.org/wiki/IOS_11#History)).

**Comment by miketaylr** [comment]
Thanks both.
