### ISSUE TITLE
The value definition of `-webkit-background-clip` is missing `none`

### ISSUE THREAD

**Issue by cdoublev** [whatwg/compat#194]
The `initial` value of [`-webkit-background-clip`](https://compat.spec.whatwg.org/#the-webkit-background-clip-property) is `none` but it is missing from its `value` definition.

> **Name**: `-webkit-background-clip`
> **Value:** `border-box | padding-box | content-box | text`
> **Initial:** `none`

**Comment by karlcow** [comment]
Checking the CSS spec for it, which is introducing text. 
https://drafts.csswg.org/css-backgrounds-4/#background-clip

https://github.com/w3c/csswg-drafts/issues/5604

@cdoublev What do you suggest?

**Comment by karlcow** [comment]
We might possibly remove the `-webkit-background-clip: text` let's open an issue about that.

**Comment by karlcow** [comment]
I open #195 for comment#12

**Comment by cdoublev** [comment]
Honestly I was only concerned about [automatic parsing of value definitions](https://github.com/w3c/csswg-drafts/issues/2921): I should be able to successfully parse `none` against the `value` definition field.

In Chrome:

```js
element.style.webkitBackgroundClip = 'initial'
console.log(getComputedStyle(target).webkitBackgroundClip) // 'border-box'
```

I think it should have been `border-box`, like for `background-clip`. 

If `background-clip` and `-webkit-background-clip` should have the same `value` space, as noted in https://github.com/w3c/csswg-drafts/issues/5604, then I'm fine with closing this issue and just ignore this property (eg. when processing extracts from [`@webref/css`](https://github.com/w3c/webref/)) until it is removed from Compat.

**Comment by karlcow** [comment]
Ah! That makes sense. So yes either way we will be deleting the text (#195) or I'll make a PR to edit the value. 
Note that for the automatic parsing https://drafts.csswg.org/css-backgrounds-4/#background-clip should give you what you need?

**Comment by cdoublev** [comment]
Yes, Chrome and Firefox (not checked in other browsers) already parse `-webkit-background-clip` as a legacy name alias of `background-clip` with the `value` space from CSS Backgrounds 4, which accepts a list of values whereas the `value` space from Compat does not.

```js
style.webkitBackgroundClip = 'text, padding-box'
console.log(style.webkitBackgroundClip) // 'text, padding-box'
console.log(style.backgroundClip) // 'text, padding-box'
style.webkitBackgroundClip = 'none'
console.log(style.webkitBackgroundClip) // 'text, padding-box'
```

**Comment by karlcow** [comment]
Safari does, Chrome doesn't yet for `-webkit-background-clip: text`. See https://bugs.chromium.org/p/chromium/issues/detail?id=1174390  
https://bugs.chromium.org/p/chromium/issues/detail?id=872114

**Comment by miketaylr** [comment]
@karlcow should we close here?

**Comment by karlcow** [comment]
yes :)
