### ISSUE TITLE
Remove `-webkit-background-clip` from compat spec.

### ISSUE THREAD

**Issue by karlcow** [whatwg/compat#195]
https://drafts.csswg.org/css-backgrounds-4/#background-clip

The current values as defined in 

```
<bg-clip> = box | border | text
```

and as noted by @gsnedders on https://github.com/w3c/csswg-drafts/issues/5604

the `-webkit-background-clip` and `background-clip` should have the same values per discussion on https://github.com/w3c/csswg-drafts/issues/4839

What would need to be checked?

* [x] the differences in values between [compat](https://compat.spec.whatwg.org/#the-webkit-background-clip-property), [CSS background clip](https://drafts.csswg.org/css-backgrounds/#background-clip), [CSS-4 background-clip](https://drafts.csswg.org/css-backgrounds-4/#background-clip)
* [x] the state of implementations. chrome for example is the only browser not having an unprefixed version of `-webkit-background-clip: text`
* [x] the state of the Web on usage (optional)
* [x] eventually create a PR

**Comment by karlcow** [comment]
| spec | values | initial |
|------|--------|------|
| compat | border-box, padding-box, content-box, text | none |
| css background | border-box, padding-box, content-box | border-box |
| css 4 background | `<box>`, border, text | border-box |

![Screen Shot 2022-06-14 at 9 32 09](https://user-images.githubusercontent.com/505230/173469375-c3f4191e-3cbd-4ef2-a78a-118f02156d9d.png)

**Comment by karlcow** [comment]
testing the values for `background-clip` in WebKit, Gecko and Blink
![Screen Shot 2022-06-14 at 10 16 53](https://user-images.githubusercontent.com/505230/173473709-279fdfd9-d9c4-4b01-be78-c2925aa23f79.png)

**Comment by karlcow** [comment]
So basically I think it probably means that can be removed from the compat spec. The only thing is that browsers can't possibly get rid of the `-webkit-` values, because many sites rely on them. 

As of today 

* [`background-clip`: 36% usage](https://chromestatus.com/metrics/css/popularity#background-clip)
* [`-webkit-background-clip`:  8%](https://chromestatus.com/metrics/css/popularity#webkit-background-clip) ❗and climbing.

**Comment by karlcow** [comment]
@foolip @lilles @miketaylr I'm happy to create a PR for it. The compat spec prose doesn't seem to be necessary here anymore.

**Comment by miketaylr** [comment]
@karlcow just so I understand, all the engines support unprefixed `background-clip`, so you propose to remove the prefixed one from the compat standard? If UAs still support a prefixed alias, I would prefer to keep it in the spec. Once everyone is committed to unship the webkit-prefixed one, it seems good to remove. 

Or do I misunderstand?

**Comment by lilles** [comment]
The prefixed version should not be removed from the compat-spec, but the "text" value does not need to have special handling anymore since that value is now part of the background-clip spec as well. Can probably make the prefixed property an alias.

**Comment by karlcow** [comment]
what @lilles said, there is no magic anymore or special case. 

1. everyone support the same thing (but [chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=872114) which doesn't have yet the unprefixed version for the `text` value).
2. the only requirement for `-webkit-background-clip` is that if it's remove from browsers it will break sites, so there's a need for it to be kept as an alias, but I'm not sure this needs to be in the compat spec, more than the CSS spec?

Or is there a specific section needed about all the prefixed properties, we can't remove even if well implemented because the Web relies on them? :)

**Comment by karlcow** [comment]
@miketaylr would that work? https://github.com/whatwg/compat/pull/196
