### ISSUE TITLE
Spec WebKitCSSMatrix

### ISSUE THREAD

**Issue by miketaylr** [whatwg/compat#2]
Feel free to link bugs where `WebKitCSSMatrix` is required for compat.

Gecko bug to implement (see blocked bugs): https://bugzilla.mozilla.org/show_bug.cgi?id=717722

Required by mobile gmail: https://github.com/webcompat/web-bugs/issues/1333#issuecomment-119797934

**Comment by miketaylr** [comment]
Blink usage counter, which has gone up to ~4%: https://www.chromestatus.com/metrics/feature/timeline/popularity/630

**Comment by foolip** [comment]
Excellent, I've long been thinking that we need just this spec, abandoning hope that this will sort itself out organically.

Note that the use counter is for the constructor, not mere access of `window.WebKitCSSMatrix`, which is likely also common as a for of WebKit detection.

@RByers, I see that in GMail there is an instance of "WebKitCSSMatrix". Even if this is spec'd and implemented elsewhere, can you file an internal bug or something?

**Comment by miketaylr** [comment]
Some reference docs:

* [Apple docs on WebKitCSSMatrix](https://developer.apple.com/library/safari/documentation/AudioVideo/Reference/WebKitCSSMatrixClassReference/index.html)

* [MSFT docs on MSCSSMatrix](https://msdn.microsoft.com/en-us/library/windows/apps/hh453593.aspx)

* [CSSMatrix (from 2009 draft of 2D transforms spec)](http://www.w3.org/TR/2009/WD-css3-2d-transforms-20090320/#cssmatrix-interface)

* [DOMMatrix spec](http://dev.w3.org/fxtf/matrix/)

**Comment by miketaylr** [comment]
Perhaps more useful:

https://github.com/WebKit/webkit/blob/master/Source/WebCore/css/WebKitCSSMatrix.idl
https://github.com/WebKit/webkit/blob/master/Source/WebCore/css/WebKitCSSMatrix.h
https://github.com/WebKit/webkit/blob/master/Source/WebCore/css/WebKitCSSMatrix.cpp

**Comment by foolip** [comment]
Assuming removal will never work out, I think our best shot is as an alias of DOMMatrix, perhaps making changes to DOMMatrix if there's some difference which cannot be squared with web compat. WDYT?

**Comment by miketaylr** [comment]
@foolip yeah, agreed. I'm about 70% done with writing it up as an alias of DOMMatrix (still learning the WebIDL/bikshed ropes..so things are slow). Hoping to commit some stuff by EOD.

**Comment by RByers** [comment]
> @RByers, I see that in GMail there is an instance of "WebKitCSSMatrix". Even if this is spec'd and implemented elsewhere, can you file an internal bug or something?

Sorry for the delay, I just realized I missed this while I was on vacation.  Poking around at the details here, it's not clear to me what the advice should be in such a bug.  Ideally we can say "use this new API that has good support in place of this deprecated API" - that's a compelling argument to push apps away from WebKit-specific dependencies.  But it looks like there are a number of issues around DOMMatrix still (eg. see [blink intent to implement thread](https://groups.google.com/a/chromium.org/forum/#!searchin/blink-dev/Geometry$20Interfaces/blink-dev/V_bJNtOg0oM/lECG9SikFwEJ)), so it's not clear that there's really consensus on what the right replacement is, right?  [MDN Suggests](https://developer.mozilla.org/en-US/docs/Web/API/DOMMatrix) that DOMMatrix is only supported by Firefox.  So perhaps we're blocked on getting a chromium owner to advance/ship geometry interfaces?

Is it trivial in practice to write code that works correctly with either API?  Or is it a bunch of work to take code designed for WebkitCSSMatrix and make it work exactly the same on other browsers?  I assume Edge already has WebkitCSSMatrix at this point?

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by miketaylr** [comment]
> Is it trivial in practice to write code that works correctly with either API? 

Unfortunately I don't think so, given that `scale` and `rotate` have different method signatures between the two APIs.

> Or is it a bunch of work to take code designed for WebkitCSSMatrix and make it work exactly the same on other browsers? 

Probably yes. There are a number of JS polyfills that just do the math themselves in JS though.

> I assume Edge already has WebkitCSSMatrix at this point?

Yeah, they mapped their `MSCSSMatrix` to `WebKitCSSMatrix`.

I think for now the answer is probably wait and see if Firefox (or others) can successfully implement `WebKitCSSMatrix` based on this spec. If Gmail was the only site left on the web using it it would probably be worth the effort to remove it.

**Comment by RByers** [comment]
> I think for now the answer is probably wait and see if Firefox (or others) can successfully implement WebKitCSSMatrix based on this spec. If Gmail was the only site left on the web using it it would probably be worth the effort to remove it.

Yeah, sounds good to me.  If we get to the point that there's specific published incremental guidance for web developers on how to easily do the right thing here, then I'm happy to file a bug for GMail to ask them to follow it.
