### ISSUE TITLE
Is this the place to make -webkit rule definition suggestions?

### ISSUE THREAD

**Issue by karl-police** [whatwg/compat#211]
Is this the place to make -webkit rule definition suggestions?

**Comment by miketaylr** [comment]
@karl-police can you clarify what you have in mind?

**Comment by karl-police** [comment]
> @karl-police can you clarify what you have in mind?

something about the scrollbar

**Comment by karl-police** [comment]
> I will close the issue here which seems more a meta discussion about what can be done more than an actual suggestion.
> 
> **BUT** about the scrollbar itself, maybe you want to check #61

how do I start a discussion?

**Comment by miketaylr** [comment]
@karl-police sorry, it's still not clear what you're asking for. Are you saying you would like to propose new CSS functionality related to scrollbars?

**Comment by karl-police** [comment]
> @karl-police sorry, it's still not clear what you're asking for. Are you saying you would like to propose new CSS functionality related to scrollbars?

For webkit, yeah, not for W3 CSS.

W3 CSS currently has denied this suggestion, causing an issue that they resolved poorly, by letting the user decide how the scrollbar should appear.

It's about overlay scrollbars. So that the scrollbar, along with the scrollbar-gutter display above the layers of the website instead of taking space.

**Comment by karl-police** [comment]
It is currently still possible to create overlay scrollbars, by using ``overflow: overlay``, but not in many browsers anymore. One where this still works is Google Chrome.

The CSS rule https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#overlay was marked depreciated. But the usage of it is still useful, if they wouldn't have depreciated it. I don't know why it was depreciated, it could have broken certain websites.

If there could be a webkit flag for overflow so that you can do overflow: -webkit-overflow or something, or -webkit-overflow: overlay, that would be interesting too.

**Comment by miketaylr** [comment]
OK, yeah - this isn't the right place. The compat standard documents things already implemented in multiple browsers today.

**Comment by karl-police** [comment]
> OK, yeah - this isn't the right place. The compat standard documents things already implemented in multiple browsers today.

What does this mean?

**Comment by miketaylr** [comment]
This is not a standard where new features are incubated or proposed. See https://compat.spec.whatwg.org/#introduction

**Comment by karl-police** [comment]
> proposed

wasn't changing the color of the scrollbar with webkit or other scrollbar related styles with webkit a new feature though?

so is webkit there as a fallback incase the browser supports something that other browsers do not?

**Comment by miketaylr** [comment]
I'm sorry, I don't understand the questions. This is no the WebKit project.

**Comment by karl-police** [comment]
> I'm sorry, I don't understand the questions. This is not the WebKit project.

Ah, because I came from here: https://github.com/w3c/csswg-drafts/issues/7717#issuecomment-1243446524


Where do the rest of the WebKit get defined from?

**Comment by miketaylr** [comment]
> Where do the rest of the WebKit get defined from?

https://webkit.org/getting-started/
