### ISSUE TITLE
Document mapping from old to new flexbox (when possible)

### ISSUE THREAD

**Issue by miketaylr** [whatwg/compat#22]
Unsure how Edge has implemented this (if via mapping/aliasing or natively), but this is how Gecko has done this.

https://bugzilla.mozilla.org/show_bug.cgi?id=1208635
https://bugzilla.mozilla.org/show_bug.cgi?id=1230708
https://bugzilla.mozilla.org/show_bug.cgi?id=1208344

**Comment by miketaylr** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1231682

**Comment by miketaylr** [comment]
Note for `-webkit-box-orient` (from https://hg.mozilla.org/integration/mozilla-inbound/rev/8172c825df87#l3.13):

```
the logical property "-webkit-box-orient" is always mapped to
flex-direction", but its values ("horizontal", "vertical") map to
different flex-direction values ("row", "column") depending on the
writing-mode.
```

**Comment by miketaylr** [comment]
So to be clear, we need to define a way to map not only properties, but also property keyword values.

**Comment by zcorpan** [comment]
I found this via https://searchfox.org/mozilla-central/rev/6201a9e0067cf6af118c6a99ae9314b8ceb2c4d5/layout/style/res/forms.css#13-54

Use counters:
https://www.chromestatus.com/metrics/css/timeline/popularity/209
https://www.chromestatus.com/metrics/css/timeline/popularity/204
