### ISSUE TITLE
Document window.browser

### ISSUE THREAD

**Issue by patrickkettner** [whatwg/compat#255]
### What is the issue with the Compatibility Standard?

During TPAC, the [WebExtensions Community Group](https://github.com/w3c/webextensions) agreed to coalesce around `window.browser` for a global namespace for extension APIs. Up until today, `window.chrome` is what is used in Chrome, and has been copied in other browsers. 

`window.browser` is already the canonical property in Firefox and Safari for extension APIs, and we at Chrome plan on aliasing  `window.chrome` to `window.browser`. In order to expose a new property on `window` in Chrome, we need to have it in a spec. As the WECG is a Community Group, we are not empowered to author specifications. We would like to add the `window.browser` as a property in the Compat spec as a User Agent defined property exposed for the use of Web Extension APIs.

**Comment by patrickkettner** [comment]
@domenic great question! That is a _much_ larger kettle of fish, but something we (the WECG) are working on.

Historically, the chrome.* APIs are only documented via the official Chrome extension documentation. This is the API that was copied by other user agents for their own compatible version of Web Extensions. It was never formally specified, and as a result there are a number of places with subtle differences. We are actively working on a WPT suite for the entirety of the Web Extensions platform to help find all of the places where there is a delta between implementations. 

Ideally, the WECG will graduate to a formal group that can publish it's own spec. Regardless of if or when that graduation occurs, the research is being done, the data collected, and the implementations becoming more aligned. Given the amount of time it will take for that to finish, it doesn't feel right to block on coalescing our documentation and API entry point on all of that work.

**Comment by xeenon** [comment]
We are supportive of this from WebKit / Apple. Safari has supported the `window.browser` namespace for extensions for a number of years now, and would like to see Chrome adopt it.

**Comment by RByers** [comment]
I thought the idea was that we wanted to reserve the API name `window.browser` on the open web without currently specifying anything inside of it. I said from a blink API owners perspective I was happy to approve shipping the exposure of a name without any properties inside it simply as providing the benefit of reserving the namespace for use by extensions. This has some non-zero compat risk (sites might already be using "window.browser" for something that wouldn't shadow) so does need to go through our blink process, so needs a spec, idlharness test, etc.

Now I don't think it's true that CGs can't author specs. They aren't empowered to author standards track documents, but we author "specs" (and ship APIs based on them in chromium) in, for example, the WICG all the time. We expect those to graduate to standards-track venues (or be removed from chromium) with time. So from a blink process perspective I had assumed your CG would just produce a non-standards-track document that uses formal spec language to define this empty API. It could also be in someone's personal github if the CG really doesn't work. Or maybe compat spec is reasonable too? I don't really have an opinion.

**Comment by karlcow** [comment]
Not much 

* WebKit [bwo](https://bugs.webkit.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&bug_status=VERIFIED&f0=OP&f1=OP&f10=CP&f2=product&f3=component&f4=alias&f5=short_desc&f7=content&f8=bug_file_loc&f9=CP&j1=OR&list_id=9910326&o2=substring&o3=substring&o4=substring&o5=substring&o6=substring&o7=matches&o8=substring&query_format=advanced&v2=window.browser&v3=window.browser&v4=window.browser&v5=window.browser&v6=window.browser&v7=%22window.browser%22&v8=window.browser). 
* Gecko [bmo](https://bugzilla.mozilla.org/buglist.cgi?f11=CP&v1=Graveyard&v5=window.browser&o8=substring&query_format=advanced&v7=window.browser&f3=OP&f10=bug_file_loc&f2=OP&f6=alias&f9=cf_crash_signature&o7=substring&f4=product&v8=window.browser&o5=substring&j3=OR&list_id=16823300&o1=notequals&f7=short_desc&f12=CP&o4=substring&f5=component&f1=classification&o9=substring&v6=window.browser&v10=window.browser&o10=substring&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&o6=substring&v9=window.browser&f8=status_whiteboard&v4=window.browser)

**Comment by patrickkettner** [comment]
@rbyers 

> I thought the idea was that we wanted to reserve the API name window.browser on the open web without currently specifying anything inside of it

Yes, that is what we had discussed, and what the PR I have for this is doing

> I don't think it's true that CGs can't author specs. They aren't empowered to author standards track documents...

Apologies, I was conflating the terms. Thanks for the correction!

@karlcow 

>  The [compat specification](https://compat.spec.whatwg.org/) is not necessary the right place either.... [its] things that browsers need to implement to have a working Web page and where the technology has not been described in any specs

That was part of my question. I think that WebExtensions are generally expected to exist in any modern browser, and while the extension specification is not written yet, there is a mountain of documentation around the existing situation. Additionally, in order for [content scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts) to work in an expected manner, there needs to be _some_ kind of global that is exposed from the web. That global is used to register event listeners and send messages to other extension surfaces. Some sites _do_ require this API to function (e.g. PWAs that only work with additional extensions, websites that use it for feature detection, etc). Given that chrome.* has been the way that WebExtensions have been written historically, and now browser.* is what all vendors are wanting to continue with, I thought that it made sense to exist in the Compat spec. 

> Is there a version of this which is absolutely necessary to be implemented by other browsers to be compatible with the current Web?
Or is it just a matter to spec it in participation with other stakeholders in the appropriate group in the right document, until it gets buy-in from implementers.


I think the biggest concern is a major website/library clobbering the `globalThis.browser` [namespace ala mootools and String.contains](https://github.com/mootools/mootools-core/issues/2402), or a new browser engine using window.browser for an unreleased purpose, making WebExtensions harder to work cross browser.


> Not much... 

FWIW, Firefox and Safari already use browser.* APIs, so it isn't likely they would have bugs as a result of not having it.

**Comment by xeenon** [comment]
@karlcow Hey there! Web Extension bugs for WebKit can be found in the [WebKit Extensions](https://bugs.webkit.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&component=WebKit%20Extensions&list_id=9915714&order=bug_id%20DESC&product=WebKit&query_format=advanced) component.

### Safari & WebKit Context

Safari has implemented `window.browser` as an alias for `window.chrome` for Web Extensions on macOS since 2020, and on iOS since 2021. The implementation is also moving to [WebKit](https://github.com/WebKit/WebKit/blob/main/Source/WebKit/WebProcess/Extensions/Cocoa/WebExtensionControllerProxyCocoa.mm#L80) as of late 2022.

Apple is absolutely committed to `window.browser` being the canonical home for Web Extension APIs in Safari and WebKit.

### Regarding Compatibility

We have not seen any compatibility issues with `window.browser` being exposed.

We have had compatibility issues when it comes to exposing `window.chrome` to webpages for [external messaging](https://github.com/WebKit/WebKit/blob/main/Source/WebKit/WebProcess/Extensions/Cocoa/WebExtensionControllerProxyCocoa.mm#L80), since exposing `window.chrome` caused too many sites to assume Safari `===` Chrome. So in the main world of webpages, we can only expose `window.browser` because of that.

**Comment by karlcow** [comment]
@xeenon 
Thanks! 
yes. `window.chrome` is the `installTrigger` of Firefox or the `navigator.standalone` of iPad Safari. Things used for not what it should be. 

What I'm trying to figure out is really why the compat spec, as you all seem to agree that there is research, spec, documentation work which could be done in the [WebExtensions Community Group](https://github.com/w3c/webextensions). It looks like there is the appropriate place for this. 

@patrickkettner 

> Given that chrome.* has been the way that WebExtensions have been written historically, and now browser.* is what all vendors are wanting to continue with, I thought that it made sense to exist in the Compat spec.

So if  there is agreement, it should be in a spec describing the API in the CG group, and then discussed the possibility to graduate it to an appropriate WG.

**Comment by marcoscaceres** [comment]
Just throwing my weight that this is not the right place to standardize this. Also just echoing what @RByers said: CGs can produce their own specs (see WICG! which produces hundreds). 

I'd suggest doing this in a CG, then, if there is enough incentive, as the W3C to create a "real" working group for formal standardization.

**Comment by patrickkettner** [comment]
Sounds like it makes sense to withdraw the issue. Thanks for all the discussion everyone!

**Comment by Rob--W** [comment]
FYI: In response to the feedback here, we (the WebExtensions CG) have started the creation of the document in the WECG repo at https://github.com/w3c/webextensions/pull/508.
