### ISSUE TITLE
Spec -webkit-background-clip: text

### ISSUE THREAD

**Issue by miketaylr** [whatwg/compat#26]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1238527 and associated bugs. Apparently this is needed (once you support `-webkit-linear-gradient`).

**Comment by miketaylr** [comment]
https://webkit.org/blog/164/background-clip-text/

**Comment by miketaylr** [comment]
The plan for Gecko is going to be (for now anyways) (see [1238550#c5](https://bugzilla.mozilla.org/show_bug.cgi?id=1238550#c5))

1) Treat `-webkit-background-clip` as an alias for `background-clip` (it does this today)
2) Add a new value "text", but only accept it if we're parsing the `-webkit-` prefixed property alias.
3) Implement the graphics/layout clipping stuff

If the CSSWG ever makes `text` a standard value for `background-clilp`, we can change the spec accordingly (and ideally move the alias to whatever spec it ends up in).

**Comment by tantek** [comment]
@miketaylr what do you think of including the text from https://webkit.org/blog/164/background-clip-text/ in a brief description of what -webkit-background-clip:text does, directly in the compat spec? I think this is appropriate because there is no intent to make this an unprefixed standard property.

**Comment by miketaylr** [comment]
Good idea @tantek, I'll find some time to do that this week.

(And we can add more technical spec bits as we go along).

**Comment by miketaylr** [comment]
OK, first stab at a definition in place. I think we can tighten up the definition as `-webkit-background-clip: text` seems to only actually clip to the text *outline*. You need `-webkit-text-fill-color: transparent` to clip to the whole foreground text color. Also would be good to reuse some of the language/concepts from https://drafts.fxtf.org/css-masking-1/.

**Comment by miketaylr** [comment]
http://www.bloomberg.com/news/features/2016-02-15/missing-malaysia-jet-mh370-weeks-away-from-keeping-secrets-forever is probably worth studying.
