### ISSUE TITLE
Prefixed properties listed in spec not present in Blink or WebKit

### ISSUE THREAD

**Issue by alancutter** [whatwg/compat#29]
The following properties are not present in the latest Blink or WebKit engines.
 - -webkit-background-attachment
 - -webkit-background-color
 - -webkit-background-image
 - -webkit-background-position
 - -webkit-background-position-x
 - -webkit-background-position-y
 - -webkit-background-repeat
 - -webkit-background

Relevant source code:
 - https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/Source/core/css/CSSProperties.in
 - http://trac.webkit.org/browser/trunk/Source/WebCore/css/CSSPropertyNames.in

**Comment by miketaylr** [comment]
Ah, interesting. At one point Edge had implemented them [(according to this list from a few months back)](https://docs.google.com/spreadsheets/d/173d1p3LkW_LWk-VMnrxGPhTobtKSpED30Fys5ZJLttA/edit#gid=51341101) in preview builds. Perhaps they realized that Blink and WebKit don't have these and removed them. Let's remove them.
