### ISSUE TITLE
Spec Element.webkitMatchesSelector()

### ISSUE THREAD

**Issue by foolip** [whatwg/compat#3]
The unprefixed API is `Element.matches()` and after shipping this in Blink, usage of the unprefixed API remains ridiculously high, the highest of any prefixed API I think:
https://www.chromestatus.com/metrics/feature/timeline/popularity/217

Had the unprefixed API been `Element.matchesSelector()` it might have been slightly better, but it's far too late for that, as `Element.matches()` has shipped in Blink, Gecko and WebKit.

Edge, on the other hand, has both `Element.mstMatchesSelector()` and `Element.webkitMatchesSelector()`, so they have already concluded that all hope is lost.

**Comment by miketaylr** [comment]
Old `matchesSelector` [w3c spec](http://www.w3.org/TR/2010/WD-selectors-api2-20100119/#matchesselector):

`matches` w3c [spec](http://www.w3.org/TR/selectors-api2/#matches): 

WHATWG DOM [spec](https://dom.spec.whatwg.org/#dom-element-matches):

I didn't follow the namechange, but it seems like it was only the name that changed. :bike: :house_with_garden:

**Comment by bzbarsky** [comment]
All hope may be more or less lost for the reason given in https://bugzilla.mozilla.org/show_bug.cgi?id=1119718#c1 (which doesn't even try to use any unprefixed version, note).  Also note that when doing use counters this one callsite is likely to overwhelm everything else, even though nothing would _break_ per se; just act slower.

I think we should simply standardize `webkitMatchesSelector` and have everyone implement it, as @foolip suggests.

**Comment by annevk** [comment]
Should we add it to DOM or add it here?

**Comment by bzbarsky** [comment]
I think this spec should really not exist other than a transitional thing; we should be adding this stuff to the actual relevant specs.  So add to DOM in this case.

**Comment by foolip** [comment]
I think this is the first prefixed API in a "proper" spec, so 😢 indeed, but it's probably for the best to abandon hope that this kind of thing would resolve itself.

**Comment by miketaylr** [comment]
> I think this spec should really not exist other than a transitional thing; we should be adding this stuff to the actual relevant specs.

+1

**Comment by dmethvin** [comment]
jQuery shipped for a long time [assuming `matchesSelector` would be the name](https://github.com/jquery/sizzle/blob/1.9.1/sizzle.js#L543-547), then when it changed to `matches` they said they were going to redo the semantics so we [took out the unprefixed name entirely](https://github.com/jquery/sizzle/blob/1.10.1/sizzle.js#L710-L713). Then it finally settled on `matches` and [we put that in](https://github.com/jquery/sizzle/blob/1.11.1/src/sizzle.js#L660-664). But there are lots of old jQuery copies out there and they won't get `matches` functionality without *some* prefixed version.

**Comment by bzbarsky** [comment]
And then the semantics didn't get redone after all.  What a mess.
