### ISSUE TITLE
Integrate WebKitCSSMatrix implementer feedback

### ISSUE THREAD

**Issue by miketaylr** [whatwg/compat#30]
cf. https://bugzilla.mozilla.org/show_bug.cgi?id=717722#c26

**Comment by miketaylr** [comment]
One last bit to address:

>  `WebKitCSSMatrix` doesn't keep track of whether a matrix is 2D while `DOMMatrix` does so the |rotate| algorithm should set the `is2D` flag appropriately. In the patch I set it to false if we try and rotate about the X or Y axis by a non-zero angle.

**Comment by zcorpan** [comment]
It should be set to *false*.

**Comment by miketaylr** [comment]
Oops.
