### ISSUE TITLE
WebKitCSSMatrix#inverse should probably throw

### ISSUE THREAD

**Issue by miketaylr** [whatwg/compat#32]
From webkit/LayoutTests/transforms/cssmatrix-3d-interface.xhtml:

```
debug("Test throwing exception from inverse");
m = new WebKitCSSMatrix("matrix(0, 0, 0, 0, 0, 0)"); // not invertible
shouldThrow('m.inverse()');
```

Currently `inverse` is defined in terms of `DOMMatrix.invertSelf` which says to do: "If the current matrix is not invertible set all attributes to NaN and set is2D to false. "

But Chrome, Safari and edge throw `DOMException` `NotSupportedError`s

**Comment by zcorpan** [comment]
Is this really necessary for Web compat? In the Geometry spec this was a deliberate change apparently

> invertSelf() and inverse() do not throw exceptions anymore.

(I don't remember rationale but could dig in mailing lists...)

**Comment by miketaylr** [comment]
Unsure if it's needed for compat, but it's at least needed to match WebKit's implementation (and pass their Layout tests). I'll try to track down some code that might rely on this, as hard as that seems.
