### ISSUE TITLE
WebKitCSSMatrix(transformList) constructor should take transform property syntax, not SVG transform attribute syntax

### ISSUE THREAD

**Issue by miketaylr** [whatwg/compat#34]
https://bugzilla.mozilla.org/show_bug.cgi?id=1241575#c1

```
It looks like WebKit is parsing the transformList using the transform property syntax [1] while DOMMatrix is parsing using the SVG transform attribute syntax as described in the SVG spec [2].

The DOMMatrix spec [3] says it should be parsed using the SVG transform attribute syntax, but we do get it slightly wrong in Gecko because according to the CSS transforms spec [4], the SVG transform attribute should also accept transform property syntax but that is currently not the case in any implementations I have tested.

[1] https://www.w3.org/TR/css-transforms-1/#propdef-transform
[2] https://www.w3.org/TR/SVG/coords.html#TransformAttribute
[3] https://drafts.fxtf.org/geometry/#dom-dommatrixreadonly-fromstring
[4] https://www.w3.org/TR/css-transforms-1/#svg-syntax
```

**Comment by zcorpan** [comment]
We should just change this in the Geometry spec.

**Comment by miketaylr** [comment]
It seems like that's how it was originally defined, but was changed after https://lists.w3.org/Archives/Public/public-fx/2014AprJun/0121.html.

In theory, if SVG transform attribute syntax accepts transform property syntax, it should just work™ (and the spec doesn't need to change) yet:

`the SVG transform attribute should also accept transform property syntax but that is currently not the case in any implementations I have tested.`

So possibly we just need to file bugs on browser engines? (unsure, need to test some things myself).

**Comment by heycam** [comment]
Yeah, the intention in SVG 2 is for `transform=""` to be a presentation attribute for the transform property, which accepts the syntax specified in CSS Transforms (i.e. both the old SVG syntax and CSS property syntax).  Without testing, I would be surprised if browsers have been updated to do that yet, though.

**Comment by zcorpan** [comment]
OK then let's leave this as is. :-)

**Comment by miketaylr** [comment]
:+1:

**Comment by miketaylr** [comment]
I documented this in https://github.com/whatwg/compat/commit/f5f11261f8826bbcfa5f0b69e6c026bed569881e -- I'll file a bug against geometry to consider the parsing quirks (not the transform property stuff).
