### ISSUE TITLE
Spec -webkit-user-select alias

### ISSUE THREAD

**Issue by miketaylr** [whatwg/compat#37]
Gecko aliases -moz-user-select to -webkit-user-select, and Edge does the same for -ms-user-select. Here's all possible values (I think `-webkit-user-select: ignore` used to exist, but was removed).

@hober wrote a summary table in https://lists.w3.org/Archives/Public/www-style/2012Jul/0541.html:

```

      +---------+-----+------+---------+------+------+-----------+
      | Engine  | all | auto | element | none | text | -moz-none |
      +---------+-----+------+---------+------+------+-----------+
      | Gecko   | ✓   | ?    | ✓       | ✓    | ✓    | ✓         |
      | Presto  | ✗   | ✗    | ✗       | ✗    | ✗    | ✗         |
      | Trident | ✗   | ✓    | ✓       | ✓    | ✓    | ✗         |
      | WebKit  | ✗   | ✓    | ✗       | ✓    | ✓    | ✗         |
      +---------+-----+------+---------+------+------+-----------+

```

@frivoal gave an update on the Presto values in that table in a later reply.

For Gecko, `none` maps to `-moz-none`. https://bugzilla.mozilla.org/show_bug.cgi?id=477152#c9 suggests way more values -- I'm looking to see what happened to those.

`element` has been renamed to `contain` in https://github.com/w3c/csswg-drafts/commit/3f1d9db96fad8d9fc787d3ed66e2d5ad8cfadd05.

https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariCSSRef/Articles/StandardCSSProperties.html only mentions `none`, `text`, and `all`.

There was a WebKit proposal for an `atomic` value (which I think turned into `all`), and I see references in LayoutTests to a `ignore` value. 

We should just map the values `none`, `text`, and `all` for the alias, because everyone supports those.

**Comment by miketaylr** [comment]
WebKit at one point had support for `-khtml-user-select: element`: https://lists.webkit.org/pipermail/webkit-dev/2006-July/001156.html

Link to `-moz-user-select` values in Gecko: https://dxr.mozilla.org/mozilla-central/rev/584870f1cbc5d060a57e147ce249f736956e2b62/layout/style/nsCSSProps.cpp#2065-2078

**Comment by frivoal** [comment]
@miketaylr This is your lucky day, just ask and your wish shall be granted!

I've written a spec for this: https://drafts.csswg.org/css-ui-4/#content-selection

If you have any feedback, I'd be most happy to receive it.

**Comment by frivoal** [comment]
Note that my spec so far does not include a requirement to support it via the vendor prefixes, but I am fine with adding it if that's required for web compat. (although I'd prefer to see it ship unprefixed first to see if that helps get rid of some part of the dependency on prefixes.)

**Comment by miketaylr** [comment]
Thanks @frivoal -- I think I'll add it here to https://compat.spec.whatwg.org/#css-prefixed-aliases now and if you decide to add it to css-ui-4 I can remove it (or we can do that when it starts to ship unprefixed).

**Comment by frivoal** [comment]
Sounds good. Can you keep your side purely about syntax, and point to my spec for behavior, to avoid accidentally encouraging behavior differences?

**Comment by frivoal** [comment]
Oh, I see that's what you did. Great then, thanks.

**Comment by miketaylr** [comment]
:+1:

**Comment by annevk** [comment]
@frivoal any reason to not just couple the definitions? That's what we do in DOM, e.g. `webkitMatchesSelector` is defined right there. Much easier for everyone.

**Comment by frivoal** [comment]
@annevk I probably should at this point. IE11 and production builds of firefox don't support this through the webkit prefix, so even though I thought that supporting it was likely needed for web compat, I did not want to outguess the browsers, as they have more reliable data than me. And the browser representatives who reviewed the spec did not ask for it.

That said, Edge and nightly versions of Firefox do now support it with the webkit prefix, so I suppose that they have now done the research an concluded it's needed. I'll check with the browser reps in the CSSWG, and most likely will include it in the spec.

**Comment by annevk** [comment]
Great. I think we should move whatever we can outside of Compat so that it's considered when those features evolve further. If we isolate it here it might get kinda forgotten. Better to just make them part of the model, however ugly.

**Comment by miketaylr** [comment]
Thanks @frivoal -- please let me know when you do and I'll remove it here.

**Comment by frivoal** [comment]
Will do. I'm confident the CSSWG will agree, but not without a heated debated first (blessing -webkit- syntax remains a hot topic). Our next conf call is Wednesday next week (we're just out of a F2F), so expect something around that time.

**Comment by frivoal** [comment]
@miketaylr sorry for the delay. This is done now, you can remove it from your spec.
https://github.com/w3c/csswg-drafts/commit/dfde9cf322831e1bc0d1385e6df68057adc08ec6

As for the "generous" flexibility on the specifics on the aliasing mechanism, this is due to MS and Moz doing it differently, with no intent to change. If/when they agree to align, I'll be happy to have the spec be more constraining, but until then, I (and the CSSWG) didn't see the point in specifying fiction.

**Comment by miketaylr** [comment]
Thanks for following up @frivoal -- I'll file an issue and get this removed soon.

**Comment by miketaylr** [comment]
Just documenting for the record @karlcow's comment here: https://github.com/webcompat/web-bugs/issues/22784#issuecomment-447699561
