### ISSUE TITLE
Spec -webkit-text-stroke

### ISSUE THREAD

**Issue by miketaylr** [whatwg/compat#40]
Originally blogged about here: https://webkit.org/blog/85/introducing-text-stroke/

See https://bugzilla.mozilla.org/show_bug.cgi?id=1248644 for why it's needed.

**Comment by miketaylr** [comment]
Actually 3 props, 1 shorthand `-webkit-text-stroke` and two longhands `-webkit-text-stroke-width` and `-webkit-text-stroke-color`.

text-stroke-width – This property allows you to specify the width of the stroke. It defaults to 0, meaning that only a fill is performed. You can specify a length for this value, and in addition the values thin, medium and thick can be used (with ‘thin’ being most like the outline behavior of OS X).
text-stroke – This property is a shorthand for the two stroke properties.

**Comment by miketaylr** [comment]
Some reading for inspiration: https://svgwg.org/svg2-draft/painting.html#StrokeProperties

**Comment by miketaylr** [comment]
For `-webkit-text-stroke-width`, the `thin`, `medium` and `thick` keywords are used to determine a "multiplier" in [StyleBuilderConverter::convertTextStrokeWidth](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/css/resolver/StyleBuilderConverter.cpp&sq=package:chromium&type=cs&l=865&rcl=1456490302) with  [ StyleBuilderConverter::convertLineWidth](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/css/resolver/StyleBuilderConverter.h&sq=package:chromium&type=cs&l=133&rcl=1456490302). 

They're the same keywords that are used for border-width.

**Comment by miketaylr** [comment]
Test page I'm using to experiment with: http://codepen.io/miketaylr/pen/QNWbYE?editors=1100

**Comment by cvrebert** [comment]
> /* looks like there's a default color here, probs currentcolor */

Pretty much:
> If not specified, the color specified by the `color` property is used.

—&nbsp;https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariCSSRef/Articles/StandardCSSProperties.html#//apple_ref/doc/uid/TP30001266--webkit-text-stroke-color

See also https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-stroke

**Comment by miketaylr** [comment]
Thx @cvrebert.

**Comment by miketaylr** [comment]
(still need to add some examples)

**Comment by miketaylr** [comment]
This seems fixed now.
