### ISSUE TITLE
"[ currentcolor | <color> ]" is redundant (currentcolor is included in <color>)

### ISSUE THREAD

**Issue by dholbert** [whatwg/compat#42]
This spec chunk...
 https://compat.spec.whatwg.org/#the-webkit-text-stroke
...says this property accepts: `<line-width> || [ currentcolor | <color> ] `

I think this should just be simplified to`<line-width> || <color>`

We don't need `currentcolor | ` there -- it's already implied by `<color>`. Specifically, the css-color-3 spec says: 
> CSS3 extends the color value to include the ‘currentColor’ keyword to allow its use with all properties that accept a <color> value. This simplifies the definition of those properties in CSS3.

**Comment by dholbert** [comment]
This document uses "currentcolor | <color>" in a bunch of places -- I believe all of them can just be collapsed to <color>.

**Comment by dholbert** [comment]
Here's one example which supports my assertion here (that we don't need to explicitly include this keyword as a valid value).

The css-backgrounds spec defines `border-color` properties:
>Name: 	border-top-color , border-right-color, border-bottom-color, border-left-color
>Value: 	`<color>`
>Initial: 	`currentColor`

https://drafts.csswg.org/css-backgrounds/#the-border-color

The initial value `currentColor` is clearly a valid value here, but the spec doesn't bother listing it explicitly on the Value field, because it's covered by `<color>`.

**Comment by miketaylr** [comment]
Thanks @dholbert!
