### ISSUE TITLE
"(including decorations and shadows)."

### ISSUE THREAD

**Issue by CJKu** [whatwg/compat#44]
https://compat.spec.whatwg.org/#the-webkit-background-clip-property

> \(including decorations and shadows\)\.
Can we not include shadow here?
Two reason
1. Chrome doesn't include shadow
2. If we include shadow here, we can't use text-path-clip, instead, we have to generate a mask from "text+text shadow", which is slower compare to text-path-clip

**Comment by miketaylr** [comment]
I'm fine with that -- following Chrome makes sense. Thanks @CJKu.

**Comment by miketaylr** [comment]
Testing w/ http://codepen.io/miketaylr/pen/eJbawd, it doesn't look like current Desktop Safari clips the shadow either.
