### ISSUE TITLE
"yes"

### ISSUE THREAD

**Issue by CJKu** [whatwg/compat#45]
https://compat.spec.whatwg.org/#the-webkit-background-clip-property

> yes
No, it's not

**Comment by upsuper** [comment]
To make it clear: this issue is about "Inherited" of `-webkit-background-clip`. It should not be an inherited property, and both the spec of `background-clip` and impl of this prefixed property agree with that. This spec should be changed.

**Comment by upsuper** [comment]
(For this kind of issues, probably filing a pull request directly is even easier)

**Comment by miketaylr** [comment]
Ah, thanks for the feedback @CJKu and @upsuper.

(pull requests for simple changes like this would be cool, but I can make a quick fix today).
