### ISSUE TITLE
-webkit-background-clip: text does not respect -webkit-text-stroke property

### ISSUE THREAD

**Issue by chenpighead** [whatwg/compat#52]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1267128

It seems Safari and Chrome both let -webkit-background-clip: text respect -webkit-text-stroke property.

**Comment by upsuper** [comment]
You should probably say something like: it is not clear from the current spec whether the clip area of `-webkit-background-clip: text` should include the text stroke.

For example, in [this testcase from our bugzilla](https://bugzilla.mozilla.org/attachment.cgi?id=8744774), Blink (and likely also WebKit) shows clear gradient stroke, while Gecko doesn't show anything.

It seems there are reasonable usecases to include the stroke for `background-clip: text`.

**Comment by chenpighead** [comment]
Much more clear!!! Thank you~

**Comment by miketaylr** [comment]
Yep, thanks @chenpighead and @upsuper. We want `-webkit-background-clip: text` to respect `-webkit-text-stroke` property.` Sites like bloomberg.com use that heavily (see https://bugzilla.mozilla.org/show_bug.cgi?id=1248644).

**Comment by miketaylr** [comment]
From https://webkit.org/blog/164/background-clip-text/, 

> This effect can be used with -webkit-text-stroke and a transparent -webkit-text-fill-color to create text with stroked outlines that is “filled” with the background.

I overlooked that oops.

**Comment by miketaylr** [comment]
(I was gonna send a PR for review, but I'm stuck on one bit of bikeshed syntax)

@chenpighead does this look OK to you?

> When `-webkit-text-stroke-color` is used with a `transparent` keyword value, or any `<color>` function that takes a non-fully opaque `<alpha-value>`, the background image clips to the text stroke path.

**Comment by upsuper** [comment]
Shouldn't it always be clipped to the text stroke outer path? I don't understand how the additional condition makes sense.

**Comment by chenpighead** [comment]
Yeah, I'm with @upsuper here, and I also work on an implementation toward this direction. @miketaylr are there other cases that we should have take into consideration?

**Comment by miketaylr** [comment]
> Shouldn't it always be clipped to the text stroke outer path?

Yeah, that makes more sense. Thanks.

> @miketaylr are there other cases that we should have take into consideration?

As far as I can tell, probably not. But I've been wrong before. ^_^

**Comment by chenpighead** [comment]
At first, I thought we would like to see the stroking result of [stroking by -webkit-background-clip: text](https://bug1267128.bmoattachments.org/attachment.cgi?id=8745875) is agree with that of [stroking by -webkit-text-stroke](https://bug1267128.bmoattachments.org/attachment.cgi?id=8745876). However, after verified on webkit and blink, things do not go this way. This would affect both the implementation and the verification (Here, I mean adding testcase) steps. Any thoughts?

**Comment by chenpighead** [comment]
Just discussed w/ xidorn offline, it turns out that they should not be the same. In the latter case, text is stroked after being filled, so a complete stroke is shown. Whereas in the former case], the -webkit-text-stroke-color is set to transparent, so the inner stroke would be filled w/ white (as -webkit-text-fill-color) and the outer stroke would be filled w/ background-color.

I'll find another way to add tests then.

**Comment by miketaylr** [comment]
@chenpighead @upsuper interested in your feedback on the change I made here when you get a chance: https://compat.spec.whatwg.org/#the-webkit-background-clip-property

**Comment by chenpighead** [comment]
@miketaylr  looks good to me. Thanks. :-)
