### ISSUE TITLE
Spec input.webkitdirectory

### ISSUE THREAD

**Issue by miketaylr** [whatwg/compat#54]
See also #53.

https://bugzilla.mozilla.org/show_bug.cgi?id=1258489

**Comment by annevk** [comment]
I guess we should add this to HTML. It would help a lot though if you could do some of the work. Happy to help though not this month.

**Comment by miketaylr** [comment]
Cool, perhaps we can chat about this in London All-hands. Not sure I'm going to have much time myself until after then.

**Comment by annevk** [comment]
Yeah, sounds good.

**Comment by foolip** [comment]
Is the all-hands a Mozilla thing?

**Comment by annevk** [comment]
Yeah, but we can VC/IRC if needed/desired. Or share your thoughts here.

**Comment by foolip** [comment]
I didn't have anything particular in mind, just curious if I was missing something awesome.

For this issue, https://www.chromestatus.com/metrics/feature/timeline/popularity/47 gives you an idea about the usage of the content and IDL attributes, combined. Not astronomical but high enough to keep if it's just going to be an alias. The sad thing about this is that this isn't available without a prefix yet. Should we add it to HTML?

**Comment by annevk** [comment]
Maybe, I thought there was some concern with the prefixed variant not offering an ideal API. We should start with standardizing the prefixed version I suppose, since everyone is doing that...

**Comment by miketaylr** [comment]
Handled by https://wicg.github.io/entries-api/, it seems.
