### ISSUE TITLE
Update Animatable to Animation type in propdef tables

### ISSUE THREAD

**Issue by chenpighead** [whatwg/compat#66]
Just found the there's a bit different from the computed value of `color` property and that of `-webkit-text-fill-color`. The computed value of `-webkit-text-fill-color` might need to be updated to be the same as [color property specification](https://drafts.csswg.org/css-color-3/#foreground).

As to the `-webkit-text-stroke-width`, would it be better to update the `Animatable: no` to be `Animation type: discrete`?

Quoted from  @SebastianZ "The W3C decided [some time ago](https://lists.w3.org/Archives/Public/www-style/2015Nov/0308.html)  to replace the "animatable" info by an "animation type" [with "discrete" as value](https://lists.w3.org/Archives/Public/www-style/2016May/0121.html) when they have a discrete value transition."

We shall probably update all the 'animatable' info in this specification as well. (Maybe in another issue?)

**Comment by chenpighead** [comment]
Here's another issue for webkit-text-stroke-width: from [CSS Values and Units Module Level 3](https://www.w3.org/TR/2016/CR-css-values-3-20160929/#absolute-lengths), I can't find "absolute width" but only "absolute length". Since the specified value of -webkit-text-stroke-width is `<line-width>` and one of the reference could be found in [CSS border-width property](https://drafts.csswg.org/css-backgrounds-3/#the-border-width) which uses "absolute length" as its computed value, perhaps we should correct "absolute width" to be "absolute length" or some similar? 

cc @miketaylr

**Comment by miketaylr** [comment]
Thanks @chenpighead -- I should have a few hours at the end of this week for spec edits.

**Comment by miketaylr** [comment]
> The computed value of -webkit-text-fill-color might need to be updated to be the same as color property specification.

@chenpighead are you sure you're looking at the right spec?

In https://drafts.csswg.org/css-color-4/#the-color-property (Dec 5th, 2016 draft), the computed value of `color` is "an RGBA color" -- which is currently what we have.

The CSS color 3 draft from July 7th, 2014 that you linked to does contain a different (more verbose) definition: https://drafts.csswg.org/css-color-3/#color0

**Comment by miketaylr** [comment]
Let's use this issue for updating to Animation type and I'll file a new issue for https://github.com/whatwg/compat/issues/66#issuecomment-263093160.

**Comment by miketaylr** [comment]
Also, @chenpighead, can I add you to the spec acknowledgements? Is "Chun-Min (Jeremy) Chen" OK, or would you prefer something else?

**Comment by miketaylr** [comment]
Hm, I can still see Animatable in addition to Animation type in the publish version, which is weird... maybe I need to update my version of bikeshed.

**Comment by miketaylr** [comment]
> Hm, I can still see Animatable in addition to Animation type in the publish version, which is weird... maybe I need to update my version of bikeshed.

OK, solved.

**Comment by chenpighead** [comment]
Sorry for the delay. I think you're right about the the computed value of -webkit-text-fill-color. No change should be made to the spec then. The update of -webkit-text-stroke-width's computed value looks good to me. I'm okay with "Chun-Min (Jeremy) Chen" added to the spec acknowledgements. Thank you for fixing these issues. :)
