### ISSUE TITLE
Add pinch-zoom token to touch-action property?

### ISSUE THREAD

**Issue by RByers** [whatwg/compat#68]
The [touch-action property](https://w3c.github.io/pointerevents/#the-touch-action-css-property) defines a number of tokens.  [Edge](https://msdn.microsoft.com/en-ca/library/windows/apps/hh767313.aspx) and [Chrome](https://www.chromestatus.com/features/5670200775016448) also ship an additional `pinch-zoom` token (and I believe Firefox plans to as well /cc @staktrace).  But it's not clear if this [will ever make it into the W3C PointerEvents spec](https://github.com/w3c/pointerevents/issues/29).

I think it's particularly important that we increase the visibility of this property (eg. [document it on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) for accessibility reasons.  Many image carousels already use `touch-action: pan-y` when they probably should be using `touch-action: pan-y pinch-zoom` in order to avoid disabling zooming for vision impared users.

It'll be a little awkward to monkey patch it in, but is it OK if I submit a PR for this?
/cc @dtapuska @teddink @navidz @mustaqahmed

**Comment by RByers** [comment]
Concretely I believe the grammar should change from:
`auto | none | [ [ pan-x | pan-left | pan-right ] || [ pan-y | pan-up | pan-down ] ] | manipulation`
To:
`auto | none | [ [ pan-x | pan-left | pan-right ] || [ pan-y | pan-up | pan-down ] || pinch-zoom ] | manipulation`

I.e. pinch-zoom may optionally be specified along with the existing `pan` values (or by itself), but not in combination with `auto`, `none` or `manipulation`.

`manipulation` then becomes a synonym for `pan-x pan-y pinch-zoom`.

**Comment by miketaylr** [comment]
Assuming this is something Gecko wants to ship eventually (or should otherwise be convinced to...), +1.

**Comment by RByers** [comment]
No such plans unfortunately since it's out of scope for the W3C PEWG charter. But I believe all PE implementations actually implement it, so it may be required for web compatibility (to avoid creating accessibility issues).

**Comment by NavidZ** [comment]
There is a test for it that we can add it to wpt as well under something like "de-facto" behaviors but not part of any specification.

**Comment by RByers** [comment]
Oh yeah, it would be great to upstream our test! It doesn't need to be "defacto" - this IS specified in the compat spec, so you can add it https://github.com/web-platform-tests/wpt/tree/master/compat.
