### ISSUE TITLE
Add Travis build status badge to README

### ISSUE THREAD

**Issue by miketaylr** [whatwg/compat#74]
This would be a cool, easy first contribution.

To fix this, grab the right image URL from https://travis-ci.org/whatwg/compat and submit a pull request adding it to the top of the README. 

Here's an example of what that would look like:

https://github.com/webcompat/webcompat.com/blob/master/README.md

See also https://docs.travis-ci.com/user/status-images/

**Comment by AkshayGulhane** [comment]
Fixed this. 
@miketaylr Please merge the pull request.

**Comment by domenic** [comment]
At this point we've got tooling enforcing that WHATWG specs never get commits merged with a failing build, so I'll take the liberty of closing this issue, since a badge doesn't seem necessary.

**Comment by miketaylr** [comment]
sgtm
