### ISSUE TITLE
Consider moving to WICG?

### ISSUE THREAD

**Issue by RByers** [whatwg/compat#76]
Ideally we'd have a place for compat stuff like this which offered some minimal IP protection so that more people could participate (eg. Microsoft, Facebook).  Should we consider moving this to, for example, a WICG repo?  I believe absolutely everything else could remain completely the same.

If things [come up](https://twitter.com/miketaylr/status/834540910989959174) before we can/want to make this decision, any objection to starting a philosophically identical spec in the WICG?  Then we can leave rationalizing the two "compat" specs down to a single one as a parallel exercise?  IMHO everything in the compat spec ideally belongs in some other spec anyway (whether the editors of that spec see it that way or not). So really we're just doing "incubation" :smile:

**Comment by domenic** [comment]
I think it's fine to consider incubating things in WICG and graduating them to this spec, but I don't think we need to demote this spec to WICG. Moving specs between standards orgs is very disruptive and should not be done lightly.

**Comment by karlcow** [comment]
@miketaylr opinions?

fwiw, when we started this. That was a discussion I had with mike. And (I guess because of my history) I was a proponent of putting that through the W3C. I don't think that would make any differences. 

Whichever decision stay here or moving to wcig, I'm happy.

**Comment by foolip** [comment]
The thing that [came up](https://twitter.com/miketaylr/status/834540910989959174) was [Implement Flash YouTube embeds rewrite to HTML](https://bugs.chromium.org/p/chromium/issues/detail?id=625984), see also the [chromium-dev intent](https://groups.google.com/a/chromium.org/d/msg/chromium-dev/BW8g1iB0jLs/uddWuBroBAAJ) by @mounirlamouri.

I don't know if the question of standardization ever came up, but given that this changes how plugins work I think HTML would be a natural place. If it can be expressed as a standalone spec with some hooks, that would be fine too of course.

As to where this spec lives, I think the people doing most of the work should get to decide that, but if there's a simpler workaround I would favor that.

**Comment by RByers** [comment]
I thought (talking with Mike offline) that in this case it would be relatively trivial and not at all disruptive in any practical sense to move it (ignoring politics of course).  But if it would actually be "very disruptive" then I'm happy with the interim step of starting a new spec, and waiting to see how much activity there is in the two places before worrying about the question of how best to reconcile the two.

Big picture, Edge had to clone a TON of webkit/blink specific behavior in order to ship using a Chrome-like UA.  It seems like they still have a bunch of debt where they've implemented behavior not defined in any spec, and are interested in helping to pay that back.  At the same time, in Chromium we're trying to survey all our non-standard IDL and efficiently decide what is a candidate for removal vs. something that should be spec'd. In practice, we've found the data from Edge to be the strongest predictor as to what is really needed for web compat vs. something we can break. So I'm very motivated to get the Edge compat folks engaged and collaborating on the spec debates here, so we can leverage their experience to make good decisions efficiently.  The longer it takes us to remove non-standard stuff, the greater the chance it's usage will increase and become part of the web forever.

**Comment by annevk** [comment]
That sounds great. They should publish their data in WICG thread or a "competing" document. Not really sure what's stopping them.

**Comment by miketaylr** [comment]
> any objection to starting a philosophically identical spec in the WICG?

Nope. I've said elsewhere that ideally the compat spec disppears entirely because things were moved to the specs where the standard counterpart lives. `WebKitCSSMatrix` is a good example of this -- it started here, but now it's an alias to `DOMMatrix` in [geometry](https://drafts.fxtf.org/geometry/). There's some other examples too, but I'm not fully awake yet.

I'd be happy to participate in a related document over in WICG, but I'd prefer to not move this one.

**Comment by cvrebert** [comment]
Given the recent WHATWG IPR changes, is this still necessary?

**Comment by foolip** [comment]
Nope :)
