### ISSUE TITLE
-webkit-line-clamp

### ISSUE THREAD

**Issue by karlcow** [whatwg/compat#80]
See https://bugzilla.mozilla.org/show_bug.cgi?id=866102

Gecko sometimes receives for the mobile version of Web sites, the `-webkit-line-clamp` feature which is not supported in Gecko at least.

Usage on the Web by Microsoft
https://developer.microsoft.com/en-us/microsoft-edge/platform/usage/css/-webkit-line-clamp/
This is used by big properties.

At the time of this issue creation:
> Used on 0.979% of scanned pages, or 2,354,088 unique URLs

No documentation found on webkit blog. 
https://www.google.com/search?q=webkit-line-clamp+site:webkit.org/blog

I didn't find the source in WebKit, but in blink
https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/style/ComputedStyle.h?type=cs&q=LineClamp+package:%5Echromium$&l=1678

https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/style/LineClampValue.h

**Comment by RByers** [comment]
Filed [chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=305376) to track getting help from the right chromium engineers on specifying our (and presumably WebKit's) behavior.

**Comment by miketaylr** [comment]
https://twitter.com/MSEdgeDev/status/969618335762612225

Wonder if anyone from the edge team wants to help spec? :) @patrickkettner, do you know who worked on it?

**Comment by miketaylr** [comment]
Oh, twitter tells me it was @cssrossen (maybe?). @cssrossen, want to collaborate on speccing out `-webkit-line-clamp` here in the compat standard?

**Comment by atanassov** [comment]
@miketaylr no promises on timeliness but certainly a reasonable thing to do.

**Comment by miketaylr** [comment]
Ah cool, this is getting taken care of https://drafts.csswg.org/css-overflow-3/#line-clamp

(cf. https://github.com/w3c/csswg-drafts/issues/390#issuecomment-371076389). 

Let's close this issue since the `-webkit-line-clamp` alias will be specced by CSS Overflow.

**Comment by SelenIT** [comment]
It seems that the standardization of unprefixed `line-clamp` will take some time, there are open issues and "at risk" longhand parts of it currently. In the same time, the prefixed version is supported nearly everywhere. Doesn't it make sense to reopen this issue and reconsider including it into Compat Standard temporarily?

**Comment by miketaylr** [comment]
I'm not opposed to including the current behavior of `-webkit-line-clamp`, but don't really have the bandwidth to do this. If someone would like to submit a PR, I have no objections to re-opening (with an eye on removing it once all the issues are solved in CSS overflow).
