### ISSUE TITLE
Spec -webkit-prefixed CSS properties that are aliases to standard unprefixed properties.

### ISSUE THREAD

**Issue by miketaylr** [whatwg/compat#9]
I suppose we'll need some kind of general intro to CSS before detailing the individual props.

Here's the CSS props that are important to Gecko (with links to their bugs), and there's probably a few more worth speccing:

https://wiki.mozilla.org/Compatibility/Mobile/Non_Standard_Compatibility#CSS_Features

Some are simple aliases to existing standards, and some will require more work (hopefully just stealing from old spec drafts).

cc @dholbert @tantek

**Comment by annevk** [comment]
Ideally all of these map to concepts already established in the CSS universe. Paging @tabatkins and @fantasai.

**Comment by miketaylr** [comment]
Yeah. I don't want to do anything more complicated than support already-defined `foo` as `webkit-foo`, ideally. For some legacy junk like gradients and old-flexbox, already-defined probably means referencing old versions of specs.

**Comment by miketaylr** [comment]
Changing the title here. For more complicated stuff, let's open new issues.

**Comment by miketaylr** [comment]
I think we have the most important "simple" ones here. We can open issues for ones I've overlooked (or discover that we need).
