### ISSUE TITLE
addRule is supported by Chrome, Safari and Edge but not Firefox

### ISSUE THREAD

**Issue by karlcow** [whatwg/compat#98]
Some websites are using `addRule` for setting styles. This is failing in Firefox.
See for example https://github.com/webcompat/web-bugs/issues/4856

**Comment by upsuper** [comment]
`CSSStyleSheet.addRule` is not part of any spec. If there are websites depending on it, we can probably add it to CSSOM spec. Could you test the behavior of that? (e.g. is it appending the rule?)

I'm happy to write the fix to Gecko, as well as the spec change and web-platform test based on the behavior you learned.

**Comment by karlcow** [comment]
Thanks @upsuper !

@foolip @RByers do you have stats on addRule?


https://codesearch.chromium.org/chromium/src/third_party/WebKit/Source/core/css/CSSStyleSheet.cpp?l=354-375&rcl=0c1d871f8c5ce28eb34f10a2bc71901772ee440f

**Comment by karlcow** [comment]
The code in Blink is simple.

**Comment by upsuper** [comment]
Oh the selector part and the declarations part are separate... That code is actually a bit more complicated than I thought, but ok, it looks straightforward enough.

**Comment by miketaylr** [comment]
Do we know that this affects a lot of sites @karlcow? I just saw the one site @ https://github.com/webcompat/web-bugs/labels/type-cssRule (possibly some are missing labels?)

**Comment by karlcow** [comment]
@miketaylr My impression is that not a lot, hence my question about https://www.chromestatus.com/metrics/feature/popularity probe to @foolip and @RByers on addRule. 

The why I opened an issue is that we have a documented place for our findings on why it should be or should not be implemented. :)

**Comment by karlcow** [comment]
If it's the one, it's 0.3% of the pages. which is surprisingly "high".
https://www.chromestatus.com/metrics/feature/timeline/popularity/220

**Comment by miketaylr** [comment]
> The why I opened an issue is that we have a documented place for our findings on why it should be or should not be implemented. :)

For sure. Just wondering if there are known bugs that I'm not aware of. Thanks.

**Comment by foolip** [comment]
The Chromium bug for this group of APIs is https://bugs.chromium.org/p/chromium/issues/detail?id=689684.

Usage is really quite high, so I think that just standardizing them is the more reasonable path. Would anyone mind that terribly?

**Comment by miketaylr** [comment]
See https://github.com/w3c/csswg-drafts/issues/3814

**Comment by cvrebert** [comment]
Resolved via https://github.com/w3c/csswg-drafts/pull/3900 ?

**Comment by karlcow** [comment]
yes and it was implemented in Firefox on May 2019
https://bugzilla.mozilla.org/show_bug.cgi?id=1545823
Documented at https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/addRule
and https://drafts.csswg.org/cssom/#legacy-css-style-sheet-members
